---
version: '2'
services:

  mysql:
    image: mysql:5.6
    hostname: some-mysql
    container_name: some-mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/user/.mysql-data-5:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    hostname: some-rabbit
    container_name: some-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

  zookeeper:
    image: zookeeper
    hostname: some-zookeeper
    container_name: some-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 zookeeper 4444"]
      interval: 5s
      timeout: 10s
      retries: 3

  cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service
    hostname: cdc-service
    container_name: cdc-service
    depends_on:
      # zookeeper:
      #   condition: service_healthy      
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy

    env_file:
      - cdc_service/environment.txt

